# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Digital_modulation/Digital_modulation.srcs/sources_1/ip/Sin_Rom/Sin_Rom.xci
# IP: The module: 'Sin_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Digital_modulation/Digital_modulation.srcs/sources_1/ip/Sin_Rom/Sin_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sin_Rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Administrator/Digital_modulation/Digital_modulation.srcs/sources_1/ip/Sin_Rom/Sin_Rom.xci
# IP: The module: 'Sin_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Digital_modulation/Digital_modulation.srcs/sources_1/ip/Sin_Rom/Sin_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sin_Rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
